#!/usr/bin/env python3
"""Generate the firmware-side warm snapshot contract from the host JSON."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "tools/dtcm-initialized-snapshot-contract.json"
OUTPUT = ROOT / "src/dtcm_snapshot_contract.rs"


def number(value: str) -> int:
    return int(value, 0)


def generate() -> str:
    contract = json.loads(CONTRACT.read_text())
    warm = contract["transitions"]["warm-entry-to-startup"]
    ranges = [
        (number(item["start"]), number(item["end"]))
        for item in warm["allowed_changes"]
    ]
    expected = sorted(
        (
            (number(item["offset"]), bytes.fromhex(item["bytes"]))
            for item in warm["expected_after"]
        ),
        key=lambda item: item[0],
    )

    for start, end in ranges:
        if not 0 <= start < end <= number(contract["size"]):
            raise SystemExit(f"invalid warm range {start:#x}..{end:#x}")
    for left, right in zip(ranges, ranges[1:]):
        if left[1] > right[0]:
            raise SystemExit(f"overlapping warm ranges {left} and {right}")
    for offset, value in expected:
        if not value or not all(
            any(start <= byte < end for start, end in ranges)
            for byte in range(offset, offset + len(value))
        ):
            raise SystemExit(f"expected value at {offset:#x} is outside warm ranges")

    lines = [
        "// @generated by tools/generate-dtcm-snapshot-contract.py; do not edit.",
        "#[cfg(feature = \"dtcm-contract-diagnostics\")]",
        "const WARM_SNAPSHOT_ALLOWED_RANGES: &[(usize, usize)] = &[",
    ]
    lines.extend(f"    (0x{start:04x}, 0x{end:04x})," for start, end in ranges)
    lines.extend([
        "];",
        "",
        "#[cfg(feature = \"dtcm-contract-diagnostics\")]",
        "const WARM_SNAPSHOT_EXPECTED: &[(usize, &[u8])] = &[",
    ])
    for offset, value in expected:
        encoded = ", ".join(f"0x{byte:02x}" for byte in value)
        lines.append(f"    (0x{offset:04x}, &[{encoded}]),")
    lines.extend([
        "];",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            raise SystemExit(f"{OUTPUT.relative_to(ROOT)} is stale; regenerate it")
        print("DTCM SNAPSHOT FIRMWARE CONTRACT PASSED")
    else:
        OUTPUT.write_text(generated)
        print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
